/** @type {import('tailwindcss').Config} */
/** @type {import('tailwindcss').Config} */
const withMT = require("@material-tailwind/react/utils/withMT");
module.exports = withMT({
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "path-to-your-node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}",
    "path-to-your-node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        sm: "480px",
        md: "768px",
        lg: "976px",
        xl: "1240px",
        "2xl": "1240px",
      },
      colors: {
        primary: "#f55266",
        success: "#33b36b",
        warning: "#fc9231",
        danger: "#f03d3d",
        info: "#2f6ed5",
        secondary: "#6c727f",
        dark: "#222934",
        "primary-text-emphasis": "#f2223b",
        "secondary-text-emphasis": "#333d4c",
        "success-text-emphasis": "#288b53",
        "info-text-emphasis": "#2358ae",
        "warning-text-emphasis": "#f67804",
        "danger-text-emphasis": "#e81212",
        "light-text-emphasis": "#333d4c",
        "dark-text-emphasis": "#181d25",
        "primary-bg-subtle": "#feeef0",
        "secondary-bg-subtle": "#f5f7fa",
        "success-bg-subtle": "#ebf7f0",
        "info-bg-subtle": "#eaf1fb",
        "warning-bg-subtle": "#fff4ea",
        "danger-bg-subtle": "#feecec",
        "light-bg-subtle": "#fff",
        "dark-bg-subtle": "#edeeef",
        "primary-border-subtle": "#fddce0",
        "secondary-border-subtle": "#e0e5eb",
        "success-border-subtle": "#d6f0e1",
        "info-border-subtle": "#d5e2f7",
        "warning-border-subtle": "#fee9d6",
        "danger-border-subtle": "#fcd8d8",
        "light-border-subtle": "#eef1f6",
        "dark-border-subtle": "#e0e5eb",
        "text-secondary": "#7D8184",
        "text-black": "#000000",
        black: "#000",
        white: "#fff",
      },
      backgroundImage: {
        "banner-1": "url('/public/images/banner/iphone-15.jpg')",
      },
      container: {
        center: true,
      },
      borderWidth: {
        10: "10px",
      },
    },
  },
});
